### ISSUE TITLE
napi_call_function calls function twice

### ISSUE THREAD

**Issue by TravisGesslein** [nodejs/abi-stable-node#324] opened 2018-05-19 18:02 UTC
I can't find a minimal example to reproduce this. I use napi_call_function to call a function that was previously set in javascript-code. The native function that calls napi_call_function runs in the usual main thread, and is initiated by a Javascript function call that maps to this native method (so if I understood it correctly, I don't need napi_make_callback). I have confirmed that the code calling napi_call_function is only called once. The javascript function is called and executes correctly, but twice. 

I do a debug output before napi_call_function, several inside the javascript function call, and one after. 

```
printf("Calling JS function\n");
status = napi_call_function(...);
if(status == napi_ok) printf("Successfully returned from function\n");
```

Inside the function call, I printf stuff like the function arguments. The resulting printout is something like

```
Calling JS Function
(several console.logs() inside the function)
(several console.logs() inside the function) (duplicated, but with some varying stuff since the function for example opens a file handle which differs the second time)
Successfully returned from function
```

In particular, the return value from the JS function that I receive on the C++ side is that of the second function call. None of the napi_ functions run anywhere in the native code previously or after returns anything other than napi_ok (I have all napi calls wrapped in a macro that checks for this). No sudden crashes or exceptions either.

Any idea what could cause this?

**Comment by mhdawson** [comment] 2018-05-19 20:28
I can't think of any reason/way we'd invoke the function twice. I think we'll need an example of code which we can use to reproduce/investigate (even if its more than minimal)

**Comment by TravisGesslein** [comment] 2018-05-19 21:11
Okay, after debugging it for a while I can't see any obvious reason why this happens. Here's a link to the full project. It's set up for Windows (64 bit), but it's possible there are linux libs in the ./api folder (not sure), but the 'libraries' section in binding.gyp would have to be changed to include those instead. Either way the linux API can be downloaded manually from here: https://www.fmod.com/download (need to register first though)

https://drive.google.com/file/d/1GYB3HJp_IhrhbaMzVQd8axScp7ZyfTCI/view?usp=sharing

index.js contains various stuff that tests the parts of the API I already ported. If you run it, you should see a lot of debug output, among them a manual call of the bankinfo.opencallback function to see if that works alright ( it does), and then soon after you should see the console.logs printed in that function being printed twice with different output for the file handle.

For me the output looks like this: 
![output](https://user-images.githubusercontent.com/2046189/40273081-f748465c-5bb9-11e8-9783-35f3f2de8df6.PNG)

The relevant behavior happens in fmod.cc in the function 'napi_fmod_callback_opencallback_async_execute'. I use an async queue that is regularly updated in the main thread in order to queue work from different threads back to the V8 thread. napi_fmod_callback_opencallback_async_execute is such a queued async function and called from AsyncWorkQueue::Update(). I need this because the library I'm trying to bind to JS calls a callback I give it from another thread.

The callback itself is retrieved from the "_opencallback" named attribute of a container object I use and hand around in the various void* data pointers in napi (using napi_ref) and then just called using napi_call_function. This callback is previously set from the javascript side (in the bankinfo.opencallback = ... line), using a custom setter for the opencallback property, because I need to translate the javascript function object into the actual C callback that is expected by the API. The setter is defined using a macro DECLARE_GENERIC_CALLBACK_SETTER_FUNC 

The entire class/struct that has this opencallback is set up in the "Studio_BankInfo" function.

Also, obligatory warning that the code is messy because I'm mostly still experimenting how to deal with standard issues (how to expose native callbacks, etc.).

**Comment by mhdawson** [comment] 2018-05-29 21:18
@digitalinfinity any chance you can look at this, I'm not setup to build/test etc on windows easily.

**Comment by mhdawson** [comment] 2021-11-15 15:31
Since there has been no interaction/recreate of this in 3 years I'm going to close this. Please let us know if that was not the right thing to do.

**Closed as completed by mhdawson** 2021-11-15 15:31 UTC
